# AutoResolve relayer — long-running process that watches the deployed
# AutonomousPredictionMarket for ResolutionFailed / GenerationFailed events
# and re-submits requestResolution / requestMarketGeneration as needed.
#
# Build from the repo root:
#   docker build -t autoresolve-relayer -f Dockerfile .
#
# Run (env vars required: PRIVATE_KEY, NEXT_PUBLIC_CONTRACT_ADDRESS):
#   docker run --rm --name autoresolve-relayer \
#     -e PRIVATE_KEY=0x... \
#     -e NEXT_PUBLIC_CONTRACT_ADDRESS=0x764Dc86246D242382c7619Fc715d0E3A64B2022b \
#     autoresolve-relayer
#
# Persist the parse-failure LRU (state/parse-failure-cache.<eoa>.json) and
# the submitted-topics Set (state/submitted-topics.<eoa>.json) across
# container restarts by mounting a volume to /app/state:
#   -v autoresolve-state:/app/state
#
# All optional env vars from .env.example (RELAYER_POLL_MS, RELAYER_MAX_TOPUP_STT,
# RELAYER_MAX_ATTEMPTS, RELAYER_VERBOSE, TOPIC_FEED_MAX_PER_TICK, etc.) are
# honored as documented in .env.example — pass with -e or via --env-file.

FROM node:20-alpine

# Matches packageManager field in package.json. corepack ships with Node 20.
RUN corepack enable && corepack prepare pnpm@10.12.1 --activate

WORKDIR /app

# Install production deps from the existing pnpm-lock.yaml so the build is
# deterministic. The relayer only imports viem; the extra deps are inherited
# from the repo's lockfile and don't bloat the image meaningfully (~250MB).
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

# Relayer + the ABI it reads at startup (lib-web/abi.json — regenerated by
# `pnpm export-abi` / `forge build`; mount a fresh copy or rebuild when
# bumping the contract). Also copy scripts/ for any shell helpers the
# operator may invoke alongside the relayer (auto-generate.sh, etc.).
# v45 (L3): removed the duplicate `COPY scripts/relayer.mjs` line above
# this block — it was fully shadowed by the `COPY scripts/ ./scripts/`
# below and just cost an extra layer in the image.
COPY lib-web/abi.json ./lib-web/abi.json
COPY scripts/ ./scripts/

# Railway rejects `VOLUME ["/app/state"]` ("docker VOLUME not supported, use
# Railway Volumes") — the volume is attached via the dashboard/CLI instead.
RUN mkdir -p /app/state

# Healthcheck: probe the shim's HTTP endpoint on /health. The shim
# returns 200 when the relayer child is alive and 503 otherwise, so
# the probe is the single source of truth for "is this container
# healthy". node:20-alpine ships node 20+ with the global `fetch`,
# so the probe is a single inline command with no extra
# dependencies. Use an async IIFE so the await chain resolves
# cleanly before process.exit — the previous inline .then().catch()
# pattern occasionally exited with code 1 even when the HTTP
# response was 200, because process.exit() ran in a microtask that
# was reordered past the promise resolution under load.
HEALTHCHECK --interval=60s --timeout=5s --start-period=10s --retries=3 \
  CMD /usr/local/bin/node -e "(async () => { try { const r = await fetch('http://localhost:3000/health'); process.exit(r.ok ? 0 : 1); } catch (e) { process.exit(1); } })()"

CMD ["node", "scripts/healthcheck.mjs"]
