import Link from 'next/link';
import { Bot, ExternalLink, Sparkles, Wand2 } from 'lucide-react';
import {
  formatCountdown,
  formatStt,
  isAgentCreated,
  MarketStatus,
  oddsPercent,
  statusLabel,
  type Market,
} from '@/lib-web/contract';
import { Tooltip } from '@/components/shared/Tooltip';

function StatusBadge({ status }: { status: MarketStatus }) {
  const styles = {
    [MarketStatus.Open]: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
    [MarketStatus.Resolving]: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
    [MarketStatus.Resolved]: 'bg-violet-500/10 text-violet-300 border-violet-500/30',
  };

  const dots = {
    [MarketStatus.Open]: 'bg-emerald-400',
    [MarketStatus.Resolving]: 'bg-amber-400',
    [MarketStatus.Resolved]: 'bg-violet-400',
  };

  return (
    <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium shadow-sm backdrop-blur-md ${styles[status]}`}>
      <span className="relative flex h-1.5 w-1.5">
        {status !== MarketStatus.Resolved && (
          <span className={`absolute inline-flex h-full w-full animate-ping rounded-full opacity-75 ${dots[status]}`}></span>
        )}
        <span className={`relative inline-flex h-1.5 w-1.5 rounded-full ${dots[status]}`}></span>
      </span>
      {statusLabel(status)}
    </span>
  );
}

function AgentResolvedStamp() {
  return (
    <Tooltip content="Outcome was decided by Somnia LLM agent validator consensus. Click the card to inspect the public receipt.">
      <div className="pointer-events-auto inline-flex items-center gap-1.5 rounded-md border border-emerald-400/30 bg-emerald-500/15 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-200 shadow-[0_0_15px_rgba(16,185,129,0.25)]">
        <Sparkles className="h-3 w-3" />
        Agent Resolved
      </div>
    </Tooltip>
  );
}

function AiCreatedStamp() {
  return (
    <Tooltip content="Market question, source, and duration were generated by a Somnia LLM Inference agent (inferToolsChat) and the createMarket call was executed on-chain by the validator subcommittee.">
      <div className="pointer-events-auto inline-flex items-center gap-1.5 rounded-md border border-cyan-400/30 bg-cyan-500/15 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-cyan-200 shadow-[0_0_15px_rgba(6,182,212,0.25)]">
        <Wand2 className="h-3 w-3" />
        AI Created
      </div>
    </Tooltip>
  );
}

export function MarketCard({
  id,
  market,
  userBet,
}: {
  id: bigint;
  market: Market;
  userBet?: { yes: bigint; no: bigint };
}) {
  const totalPool = market.yesTotal + market.noTotal;
  const yesOdds = oddsPercent(market.yesTotal, market.noTotal, 'yes');
  const yourSide =
    userBet && userBet.yes > 0n
      ? `YES · ${formatStt(userBet.yes)}`
      : userBet && userBet.no > 0n
        ? `NO · ${formatStt(userBet.no)}`
        : null;

  const isResolved = market.status === MarketStatus.Resolved;
  const isAiCreated = isAgentCreated(market.creator);
  // v33 (H1): when status is Resolving, prefer inferenceRequestId over
  // parseRequestId. The parse callback may have already succeeded (status is
  // Resolving and inferenceRequestId > 0); in that case the inference is the
  // live operation, but the pre-v33 logic linked the parse receipt (which is
  // already "completed") and the user missed the live inference. Fall through
  // to parseRequestId only when inference hasn't started yet.
  const receiptId = isResolved && market.inferenceRequestId > 0n
    ? market.inferenceRequestId
    : !isResolved && market.status === MarketStatus.Resolving
      ? (market.inferenceRequestId > 0n ? market.inferenceRequestId : market.parseRequestId)
      : 0n;

  return (
    <Link
      href={`/market/${id.toString()}`}
      className="group relative flex min-h-52 flex-col rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur-xl shadow-xl shadow-black/20 transition-all duration-300 ease-out hover:-translate-y-1 hover:border-cyan-400/40 hover:shadow-[0_8px_30px_rgb(6,182,212,0.15)] hover:bg-white/10"
    >
      {(isResolved || isAiCreated) && (
        <div className="pointer-events-none absolute right-5 top-5 z-10 flex flex-col items-end gap-1.5">
          {isAiCreated && <AiCreatedStamp />}
          {isResolved && <AgentResolvedStamp />}
        </div>
      )}

      <div className={`mb-4 flex items-start justify-between gap-3 ${isResolved ? 'pr-32' : ''}`}>
        <h3 className="line-clamp-3 text-lg font-bold leading-snug text-white transition-colors group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-cyan-200">
          {market.question}
        </h3>
        <StatusBadge status={market.status} />
      </div>

      <p className="mb-5 truncate rounded-lg border border-white/5 bg-black/40 px-3 py-2 text-xs text-zinc-400 shadow-inner">
        {market.resolutionSource}
      </p>

      <div className="mb-5">
        <div className="mb-1.5 flex justify-between text-xs font-semibold tracking-wide">
          <span className="text-emerald-400 drop-shadow-sm">Yes {yesOdds.toFixed(0)}%</span>
          <span className="text-rose-400 drop-shadow-sm">No {(100 - yesOdds).toFixed(0)}%</span>
        </div>
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-rose-500/20 shadow-inner">
          <div
            className="h-full rounded-full bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)] transition-all duration-500 ease-out"
            style={{ width: `${yesOdds}%` }}
          />
        </div>
      </div>

      <div className="mt-auto space-y-4 text-sm">
        <div className="grid grid-cols-2 gap-3">
          <div className="rounded-xl bg-black/30 p-3 shadow-inner">
            <div className="text-xs font-medium uppercase tracking-wider text-zinc-500">Pool</div>
            <div className="mt-1 text-lg font-bold text-white drop-shadow-sm">{formatStt(totalPool)}</div>
          </div>
          <div className="rounded-xl bg-emerald-500/10 p-3 shadow-inner border border-emerald-500/10">
            <div className="text-xs font-medium uppercase tracking-wider text-emerald-400/80">YES odds</div>
            <div className="mt-1 text-lg font-bold text-emerald-300 drop-shadow-sm">{yesOdds.toFixed(0)}%</div>
          </div>
        </div>

        {receiptId > 0n && (
          <Link
            href={`/receipt/${receiptId.toString()}`}
            target="_blank"
            rel="noreferrer"
            onClick={(e) => e.stopPropagation()}
            className="pointer-events-auto inline-flex items-center gap-1.5 rounded-md border border-cyan-400/20 bg-cyan-400/5 px-2.5 py-1.5 text-[11px] font-semibold text-cyan-200 transition hover:border-cyan-400/40 hover:bg-cyan-400/15"
          >
            <Bot className="h-3 w-3" />
            {isResolved ? 'View on Agent Explorer' : 'View live receipt'}
            <ExternalLink className="h-3 w-3 opacity-70" />
          </Link>
        )}

        <div className="flex items-center justify-between gap-3 border-t border-white/10 pt-4 mt-2">
          <span className="truncate text-xs font-semibold text-violet-300">
            {yourSide ? `Your bet: ${yourSide}` : 'No position yet'}
          </span>
          <span className="shrink-0 text-right text-xs font-bold text-cyan-300 uppercase tracking-wide">
            {isResolved
              ? market.outcome
                ? 'Resolved YES'
                : 'Resolved NO'
              : formatCountdown(market.endTime)}
          </span>
        </div>
      </div>
    </Link>
  );
}
